image: node:16

services:
  - postgres:14.1

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

stages:
  - build
  - test_frontend

build:
  stage: build
  script:
    - "cd frontend; yarn install"
    - "cd .."
    - "cd backend; yarn install"

test_frontend:
  stage: test_frontend
  needs: [build]
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - "cd frontend; yarn test"
