image: node:16

services:
  - postgres:14.1

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

stages:
  - build

build:
  stage: build
  script:
    - "cd frontend; yarn install"
    - "cd .."
    - "cd backend; yarn install"
