version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  backend:
    build: ./backend
    ports:
      - 4000:4000
    links:
      - "database:postgres"
  database:
    build:
      context: .
      dockerfile: Postgres.Dockerfile
    ports:
      - 4001:5432
